resolver: lts-12.26

packages:
- '.'

extra-deps:
  - currency-codes-3.0.0.1

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Extra directories used by stack for building
extra-include-dirs:
- /usr/local/opt/openssl/include
extra-lib-dirs:
- /usr/local/opt/openssl/lib
